### PR TITLE
add method $model->translateOrNew($locale)

### PR DESCRIPTION
**Pull request by Levgenij**

### CODE REVIEW

**Comment by acasar** [comment]
@Levgenij can you just reformat to PSR2 (tabs->spaces) and this is good to merge. Thanks!

**Comment by Levgenij** [comment]
done

**Comment by acasar** [comment]
@Levgenij Seems like only the line 236 was updated, other lines still have tabs?

**Comment by Levgenij** [comment]
done )

**Comment by acasar** [comment]
@Levgenij Merged as part of https://github.com/laraplus/translatable/commit/4eb4ecc3c43148093c74961de40871cd48ccd6df

**Pull request closed without merging**
